esphome:
  name: warmte-meter-mbus
  friendly_name: warmte-meter-mbus

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: custom_components
    
# Enable logging
logger:
  baud_rate: 0
  level: INFO 
  logs:
    sensor: INFO
    warmtemetermbus.sensor: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "PsKaCvrdD8AjEdWsv7b32V2KGBf7kicJAqhE+/zU1H8="

ota:
  password: "e5264b2500ef5b812b82d4342c5a60f6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Warmte-Meter-Mbus"
    password: "MHcfSqvZc6fe"

uart:
  baud_rate: 2400
  # WROOM Breadboard / PCB: TX 17, RX 16
  # tx_pin: 17
  # rx_pin: 16
  # WROVER PCB: TX 19, RX 18
  tx_pin: 19
  rx_pin: 18
  data_bits: 8
  parity: EVEN
  stop_bits: 1

switch:
  - platform: template
    name: MbusSwitch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    id: readmbus
    turn_on_action:
    - lambda: |-
        id(heatmetermbus).enableMbus();
    turn_off_action:
    - lambda: |-
        id(heatmetermbus).disableMbus();

interval:
  - interval: 8sec
    then:
      - lambda: |-
            id(heatmetermbus).readMbus();

heatmeter_mbus:
  id: heatmetermbus

sensor:
  - platform: heatmeter_mbus
    name: naam 1
    index: 1
  - platform: heatmeter_mbus
    name: naam 2
    index: 4
